# Path to the input CSV file
# Option 1: Specify a single file
# input_file: input/plot_single.csv

# Option 2: Specify multiple files
# input_files:
#   - input/plot1.csv
#   - input/plot2.csv

# If neither is specified, all CSVs in the input/ folder will be processed
# input_file: input/input.csv

# Header cleanup rules (strings to remove from column names)
header_cleanup:
  - "Ave. (C)"
  - "(C)"

# Plot dimensions (width, height)
plot_size: [12, 7.5]

# Font sizes for different elements
font_sizes:
  title: 14      # Title font size
  legend: 10     # Legend font size
  axis: 12       # Axis labels font size

# Indices of columns to plot (excluding time column) = [1, 3, 5] would plot the 2nd, 4th, and 6th columns
# Leave empty or omit to plot all available columns = []
columns_to_plot: [1,3]

# Sampling rate in milliseconds
sampling_rate_ms: 100

# Time window in seconds [start, end]
# Leave empty or omit to plot full range
time_window: []

# Output directory (optional â€” defaults to "output/")
# output_dir: output

# Output formats to save the plot
# Supports jpeg and pdf
# Specify one or multiple formats like this: ["jpeg"] or ["jpeg", "pdf"]
# If the plot shall not be safed, use an empty list: []
save_formats: ["jpeg", "pdf"]
